#ifndef _CONSTANTS_H_
#define _CONSTANTS_H_

#define VENDOR_ID_MICROSOFT 0x045e
#define PRODUCT_ID_MICROSOFT_XBOX_WIRELESS_CONTROLLER 0x0b12

#define VENDOR_ID_NINTENDO 0x057e
#define PRODUCT_ID_NINTENDO_SWITCH_PRO_CONTROLLER 0x2009
#define PRODUCT_ID_NINTENDO_SWITCH_JOYCON_L 0x2006
#define PRODUCT_ID_NINTENDO_SWITCH_JOYCON_R 0x2007
#define PRODUCT_ID_NINTENDO_SWITCH_JOYCON_GRIP 0x200e

#endif
